- method: fetch_cluster
  input:
    fetch_cluster:
      linearizable: true
  output:
    fetch_cluster:
      - data:
          leader_id: 0
          term: 2
          cluster_id: 123
          members:
            - id: 0
              name: S0
              addrs:
                - A0
            - id: 1
              name: S1
              addrs:
                - A1
            - id: 2
              name: S2
              addrs:
                - A2
            - id: 3
              name: S3
              addrs:
                - A3
            - id: 4
              name: S4
              addrs:
                - A4
          cluster_version: 1
      - data:
          leader_id: 0
          term: 2
          cluster_id: 123
          members:
            - id: 0
              name: S0
              addrs:
                - A0
            - id: 1
              name: S1
              addrs:
                - A1
            - id: 2
              name: S2
              addrs:
                - A2
            - id: 3
              name: S3
              addrs:
                - A3
            - id: 4
              name: S4
              addrs:
                - A4
          cluster_version: 1
      - data:
          leader_id: 0
          term: 2
          cluster_id: 123
          members:
            - id: 0
              name: S0
              addrs:
                - A0
            - id: 1
              name: S1
              addrs:
                - A1
            - id: 2
              name: S2
              addrs:
                - A2
            - id: 3
              name: S3
              addrs:
                - A3
            - id: 4
              name: S4
              addrs:
                - A4
          cluster_version: 1
- method: propose
  input:
    propose:
      propose_id:
        seq_num: 1
  output:
    propose:
      data:
        type: range
        range:
          count: 1
- method: propose
  input:
    propose:
      propose_id:
        seq_num: 2
  output:
    propose:
      error:
        code: 3
        message: duplicated
- method: propose
  input:
    propose:
      propose_id:
        seq_num: 3
  output:
    propose:
      data:
        type: range
        range:
          count: 1
- method: propose
  input:
    propose:
      propose_id:
        seq_num: 4
  output:
    propose:
      data:
        type: range
        range:
          count: 1
- method: propose
  input:
    propose:
      propose_id:
        seq_num: 5
  output:
    propose:
      data:
- method: wait_synced
  input:
    wait_synced:
      propose_id:
        seq_num: 6
  output:
    wait_synced:
      data:
        execute_result:
          type: range
          range:
            count: 1
        after_sync_result:
          revision: 1
- method: propose
  input:
    propose:
      propose_id:
        seq_num: 7
  output:
    propose:
      data:
        type: range
        range:
          count: 1
- method: wait_synced
  input:
    wait_synced:
      propose_id:
        seq_num: 7
  output:
    wait_synced:
      data:
        execute_result:
          type: range
          range:
            count: 1
        after_sync_result:
          revision: 1
- method: propose
  input:
    propose:
      propose_id:
        seq_num: 8
  output:
    propose:
      data:
        type: range
        range:
          count: 1
- method: wait_synced
  input:
    wait_synced:
      propose_id:
        seq_num: 8
  output:
    wait_synced:
      data:
        execute_result:
          type: range
          range:
            count: 1
        after_sync_result:
          revision: 1
- method: propose
  input:
    propose:
      propose_id:
        seq_num: 9
  output:
    propose:
      error:
        code: 3
        message: shutting down
- method: wait_synced
  input:
    wait_synced:
      propose_id:
        seq_num: 9
  output:
    wait_synced:
      data:
        execute_result:
          type: range
          range:
            count: 1
        after_sync_result:
          revision: 1
